### ISSUE TITLE
[Feature] add watch mode for development

### ISSUE THREAD

**Issue by mnlbox** [HarveyD/react-component-library#16]
Hi,

I think a watch mode feature also can be very useful in this repo. Something like watch mode in https://github.com/transitive-bullshit/create-react-library and microbundle.
It is possible in Rollup, right?

**Comment by HarveyD** [comment]
You just need to add:
```
"build:watch": "rollup -c --watch",
```
to your `package.json` scripts.

**Comment by shadesOfcodes** [comment]
the example app, doesn't get updated with the latest build automatically, how do i achieve that
