### ISSUE TITLE
Why you don't use official TypeScript plugin?

### ISSUE THREAD

**Issue by mnlbox** [HarveyD/react-component-library#21]
Hi @HarveyD,
As I checked rollup has an official TypeScript plugin here:
https://github.com/rollup/plugins/tree/master/packages/typescript

Why you prefer `rollup-plugin-typescript2` to this? Any specific feature exists in this?

**Comment by HarveyD** [comment]
Yeah good question. I don't think you can go wrong using either. From the `rollup-plugin-typescript2`, it's said that:
> This version is somewhat slower than original, but it will print out typescript syntactic and semantic diagnostic messages (the main reason for using typescript after all).

Which I find to be helpful in development :).
