### ISSUE TITLE
Module not found: Can't resolve 'styled-components'

### ISSUE THREAD

**Issue by dreamsparkx** [HarveyD/react-component-library#22]
When user runs the build command and import it in the project, it throws an error:

```
Module not found: Can't resolve 'styled-components'
```

**Comment by dreamsparkx** [comment]
Should it be installed as peer dependency?

**Comment by dreamsparkx** [comment]
Got it, removed styled-components from external array in rollup config.

**Comment by HarveyD** [comment]
Hey @dreamsparkx. Yeah can either be included as a `peerDependency`, or we can bundle `styled-components` with the Rollup output.

**Comment by dreamsparkx** [comment]
@HarveyD Thank you very much.
