### ISSUE TITLE
How do I get additional stuff in storybook to show at the bottom?

### ISSUE THREAD

**Issue by jauggy** [HarveyD/react-component-library#25]
I'm very new to storybook. I followed your tutorial and when I ran ```yarn storybook``` it worked but I'm missing all the additional stuff at the bottom that I see [here]( https://storybook.js.org/ff519d6518900d4be0ce86bbf3655913/example-button-args.png).

**Comment by HarveyD** [comment]
These are called Storybook Addons, that you're going to have to add yourself: https://storybook.js.org/addons/
