### ISSUE TITLE
[Bug] styled-component still generate scss file

### ISSUE THREAD

**Issue by franckLdx** [HarveyD/react-component-library#34]
in branch Branch styled-component npm run generate YourComponentName generates a component using a scss file.
I think that util/template/component.scss.js should be deleted (index.js and component.js should be updated accordingly).

**Comment by HarveyD** [comment]
I've tried to replicate this. No `scss.js` files were generated. Make sure you clean the `build` directory before building otherwise you can see some old artefacts that may have been generated on a different version of the branch.
