### ISSUE TITLE
Unable to use css/scss module in webpack or rollup.

### ISSUE THREAD

**Issue by FreakyHarsh** [HarveyD/react-component-library#39]
When i do this: 

`import styles from "./TestComponent.module.scss";
`
I get a typescript error. 
`Cannot find module './TestComponent.module.scss' or its corresponding type declarations.
`
I used @ts-ignore but then on `npm run storybook` i get an error:
```
ERROR in ./src/TestComponent/TestComponent.tsx
Module not found: Error: Can't resolve './TestComponent.module.scss' in '/Users/harshboricha/Desktop/rcl2/src/TestComponent'
```

**Comment by MaximKudryavtsev** [comment]
Hello!
I faced with this issue too and found  decision. You need creat *.d.ts file and paste this code:
```
declare module '*.less' {
  const content: Record<string, string>;
  export default content;
}
```

It helped me and I hope it will help you

**Comment by FreakyHarsh** [comment]
Thank you, It worked.
I create a `global.d.ts` file with content
```
declare module "*.scss";
declare module '*.less' {
  const content: Record<string, string>;
  export default content;
}
```

**Comment by celineotter** [comment]
I have not been successful at compiling with css modules + scss
even with the `global.d.ts` above 
and extending the rollup plugin definition as:
```
    postcss({
        modules: true,
        use: ["sass"]
    }),
```

@disguised-uchiha  or Harvey any other suggestions to try please?
rollup has been such a headache to get this working when it is out of the box with webpack CRA.
