### ISSUE TITLE
Getting errors after npm install

### ISSUE THREAD

**Issue by theone3nu** [HarveyD/react-component-library#47]
I just cloned the repo and typed npm install but i am getting the following errors.

`npm ERR! npm ERR!   c++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.5.5"' 
npm ERR! npm ERR! ../src/libsass/src/ast.hpp:1616:25: warning: loop variable 'denominator' creates a copy from type 'const std::__1::basic_string<char>' [-Wrange-loop-construct]
npm ERR! npm ERR!         for (const auto denominator : denominators)
`
node version 16.10.0
npm version 8.1.3

**Comment by waqaspathan00** [comment]
Bumping this, can a proper install guide be made?

**Comment by HarveyD** [comment]
I've removed the dependency on node-sass which I suspect is causing this issue. Please let me know if this issue continues to happen.
